### ISSUE TITLE
[ Backend ] Integrate AWS ElasticSearch for searching database

### ISSUE THREAD

**Issue by alanj1998** [PAKDProject/elance-serverless-backend#30]
#### *To do*
Integrate AWS ElasticSearch for searching database
____
#### *Definition of Done*
An index is prepared to search by first name and last name.
___
#### *Test*
1. Search Bob by his first name, John or last name THICC.

**Comment by BlueishLeaf** [comment]
Whoopsie wrong issue

**Comment by alanj1998** [comment]
[LocalStack](https://github.com/localstack/localstack) 
Check this out for offline cloudsearch!
